trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS S3'
    regionName: 'eu-west-2'
    bucketName: 'www.lap-it.com'
    globExpressions: '**'